let tom = new Cat('tom',3,30)
let jerry = new Rat('jerry',1,10,true)
tom.catCall()
jerry.mouseCall()
tom.catchMouse(jerry)
tom.eatMouse(jerry)
console.log(jerry.checkStatus())
console.log(tom.getWeight())
tom.setSpeed(5)
console.log(tom.getSpeed())
tom.catchMouse()
